export const destinationsData = [
    {
      id: 1,
      name: 'Marrakech, Morocco',
      continent: 'africa',
      price: 'luxury',
      duration: 'medium',
      image: 'https://i.ibb.co/kXRZgXB/Marrackech.jpg',
      description: 'Experience the magic of the Red City with its bustling souks and majestic palaces.',
      days: '4 Days',
      rating: '4.8/5 (156 reviews)',
      priceValue: '1200 DHS',
      popular: true
    },
    {
      id: 2,
      name: 'Chefchaouen, Morocco',
      continent: 'africa',
      price: 'moderate',
      duration: 'short',
      image: 'https://i.ibb.co/PwxwhJN/chefchaouen.jpg',
      description: 'Discover the enchanting Blue Pearl of Morocco nestled in the Rif Mountains.',
      days: '3 Days',
      rating: '4.7/5 (98 reviews)',
      priceValue: '900 DHS',
      popular: true
    },
    {
      id: 3,
      name: 'Fes, Morocco',
      continent: 'africa',
      price: 'premium',
      duration: 'medium',
      image: 'https://i.ibb.co/Zfyqndd/istockphoto-1043025646-612x612.jpg',
      description: "Explore the medieval medina and ancient tanneries in Morocco's cultural capital.",
      days: '4 Days',
      rating: '4.6/5 (134 reviews)',
      priceValue: '1100 DHS',
      popular: true
    },
    {
      id: 4,
      name: 'Casablanca, Morocco',
      continent: 'africa',
      price: 'premium',
      duration: 'short',
      image: 'https://i.ibb.co/F3VSW2s/istockphoto-1282606692-612x612.jpg',
      description: "Visit the magnificent Hassan II Mosque in Morocco's economic powerhouse.",
      days: '3 Days',
      rating: '4.4/5 (145 reviews)',
      priceValue: '1300 DHS',
      popular: false
    },
    {
      id: 5,
      name: 'Essaouira, Morocco',
      continent: 'africa',
      price: 'moderate',
      duration: 'short',
      image: 'https://i.ibb.co/RTssyqZ/istockphoto-1166268360-612x612.jpg',
      description: 'Experience the coastal charm of this artistic windswept city.',
      days: '3 Days',
      rating: '4.6/5 (87 reviews)',
      priceValue: '950 DHS',
      popular: true
    },
    {
      id: 6,
      name: 'Tangier, Morocco',
      continent: 'africa',
      price: 'moderate',
      duration: 'short',
      image: 'https://i.ibb.co/dJ7Hr9x/istockphoto-1147314604-612x612.jpg',
      description: 'Explore the gateway between Africa and Europe in this vibrant port city.',
      days: '3 Days',
      rating: '4.3/5 (92 reviews)',
      priceValue: '1000 DHS',
      popular: false
    },
    {
      id: 7,
      name: 'Agadir, Morocco',
      continent: 'africa',
      price: 'luxury',
      duration: 'medium',
      image: 'https://i.ibb.co/WDWsjH8/Agadir.jpg',
      description: "Relax on golden beaches in Morocco's premier coastal resort destination.",
      days: '5 Days',
      rating: '4.7/5 (167 reviews)',
      priceValue: '1400 DHS',
      popular: true
    },
    {
      id: 8,
      name: 'Rabat, Morocco',
      continent: 'africa',
      price: 'premium',
      duration: 'short',
      image: 'https://i.ibb.co/qrjhnVd/Rabat.jpg',
      description: "Discover the perfect blend of history and modernity in Morocco's capital.",
      days: '3 Days',
      rating: '4.4/5 (78 reviews)',
      priceValue: '1050 DHS',
      popular: false
    },
    {
      id: 9,
      name: 'Meknes, Morocco',
      continent: 'africa',
      price: 'budget',
      duration: 'short',
      image: 'https://i.ibb.co/VVzz2gt/istockphoto-1037605032-612x612.jpg',
      description: 'Explore the imperial city known for its Spanish-Moorish architecture.',
      days: '2 Days',
      rating: '4.5/5 (65 reviews)',
      priceValue: '850 DHS',
      popular: false
    },
    {
      id: 10,
      name: 'Ouarzazate, Morocco',
      continent: 'africa',
      price: 'premium',
      duration: 'short',
      image: 'https://i.ibb.co/PGjdjwy/istockphoto-502546130-612x612.jpg',
      description: 'Visit the Hollywood of Morocco and gateway to the Sahara Desert.',
      days: '3 Days',
      rating: '4.6/5 (89 reviews)',
      priceValue: '1150 DHS',
      popular: true
    },
    {
        id: 11,
        name: 'Ifrane, Morocco',
        continent: 'africa',
        price: 'mid-range',
        duration: 'short',
        image: 'https://i.ibb.co/R23zPpm/istockphoto-1401747491-612x612.jpg',
        description: 'Discover the beauty of the Middle Atlas mountains and the Swiss-like charm of Ifrane.',
        days: '2 Days',
        rating: '4.7/5 (135 reviews)',
        priceValue: '700 DHS',
        popular: true,
      },
    {
      id: 12,
      name: 'Asilah, Morocco',
      continent: 'africa',
      price: 'budget',
      duration: 'short',
      image: 'https://i.ibb.co/br0WKG3/Asilah.jpg',
      description: 'Discover this charming coastal town with its artistic heritage.',
      days: '2 Days',
      rating: '4.4/5 (45 reviews)',
      priceValue: '800 DHS',
      popular: false
    },
    {
      id: 13,
      name: 'Merzouga, Morocco',
      continent: 'africa',
      price: 'luxury',
      duration: 'medium',
      image: 'https://i.ibb.co/5s8yYWZ/istockphoto-649723312-612x612.jpg',
      description: 'Experience the magic of the Sahara Desert with luxury desert camps.',
      days: '4 Days',
      rating: '4.9/5 (178 reviews)',
      priceValue: '1500 DHS',
      popular: true
    },
    {
        id: 14,
        name: 'Oujda, Morocco',
        continent: 'africa',
        price: 'budget',
        duration: 'short',
        image: 'https://i.ibb.co/svR1tgz/Oujda.jpg',
        description: 'Explore the eastern charm of Morocco with historical sites and vibrant souks.',
        days: '3 Days',
        rating: '4.5/5 (92 reviews)',
        priceValue: '500 DHS',
        popular: false,
      },
      {
        id: 15,
        name: 'Legzira, Morocco',
        continent: 'africa',
        price: 'mid-range',
        duration: 'short',
        image: 'https://i.ibb.co/H2c9hbj/legzira.jpg',
        description: 'Admire the stunning red rock arches and relax by the beach in this hidden gem.',
        days: '2 Days',
        rating: '4.8/5 (110 reviews)',
        priceValue: '800 DHS',
        popular: true,
      },
      {
        id: 16,
        name: 'Larache, Morocco',
        continent: 'africa',
        price: 'budget',
        duration: 'short',
        image: 'https://i.ibb.co/th7r8qW/Larache.webp',
        description: 'Discover the serene beaches and rich history of this coastal city in northern Morocco.',
        days: '2 Days',
        rating: '4.6/5 (87 reviews)',
        priceValue: '600 DHS',
        popular: false,
      },
      {
        id: 17,
        name: 'Laâyoune, Morocco',
        continent: 'africa',
        price: 'mid-range',
        duration: 'medium',
        image: 'https://i.ibb.co/dJ7446V/Laayoune.png',
        description: "Experience the charm of the Sahara and the vibrant culture of Morocco's southern city.",
        days: '3 Days',
        rating: '4.7/5 (102 reviews)',
        priceValue: '900 DHS',
        popular: true,
      },
      {
        id: 18,
        name: 'Tafraoute, Morocco',
        continent: 'africa',
        price: 'mid-range',
        duration: 'short',
        image: 'https://i.ibb.co/J7d5vFf/Tafraoute.jpg',
        description: 'Explore the stunning pink granite mountains and vibrant culture of this unique village in the Anti-Atlas.',
        days: '3 Days',
        rating: '4.7/5 (98 reviews)',
        priceValue: '700 DHS',
        popular: true,
      }
  ];