export const destinationsData = [
  {
      id: 1,
      name: 'Paris, France',
      continent: 'europe',
      price: 'luxury',
      duration: 'medium',
      image: '../images/destinations/Paris.jpg',
      description: 'Experience the romance of the City of Light with our curated Parisian adventure.',
      days: '5 Days',
      rating: '4.8/5 (120 reviews)',
      priceValue: '$999',
      popular: true
  },
  {
      id: 2,
      name: 'Bali, Indonesia',
      continent: 'asia',
      price: 'moderate',
      duration: 'long',
      image: '../images/destinations/Bali.jpg',
      description: 'Discover the perfect blend of culture, nature, and relaxation in Bali.',
      days: '7 Days',
      rating: '4.9/5 (200 reviews)',
      priceValue: '$799',
      popular: true
  },
  {
      id: 3,
      name: 'Santorini, Greece',
      continent: 'europe',
      price: 'luxury',
      duration: 'medium',
      image: '../images/destinations/Santorini.jpg',
      description: 'Experience the magic of the Mediterranean in stunning Santorini.',
      days: '6 Days',
      rating: '4.7/5 (150 reviews)',
      priceValue: '$899',
      popular: false
  },
  {
      id: 4,
      name: 'Tokyo, Japan',
      continent: 'asia',
      price: 'luxury',
      duration: 'long',
      image: '../images/destinations/Tokyo.jpg',
      description: 'Immerse yourself in the perfect blend of tradition and modernity in vibrant Tokyo.',
      days: '8 Days',
      rating: '4.9/5 (180 reviews)',
      priceValue: '$1299',
      popular: true
  },
  {
      id: 5,
      name: 'Cape Town, South Africa',
      continent: 'africa',
      price: 'moderate',
      duration: 'medium',
      image: '../images/destinations/Cape-Town.jpg',
      description: 'Explore the stunning landscapes and rich culture of the Mother City.',
      days: '6 Days',
      rating: '4.8/5 (90 reviews)',
      priceValue: '$899',
      popular: false
  },
  {
      id: 6,
      name: 'New York City, USA',
      continent: 'northAmerica',
      price: 'luxury',
      duration: 'medium',
      image: '../images/destinations/New-York.jpg',
      description: 'Experience the energy and excitement of the city that never sleeps.',
      days: '5 Days',
      rating: '4.7/5 (250 reviews)',
      priceValue: '$1099',
      popular: false
  },
  {
      id: 7,
      name: 'Machu Picchu, Peru',
      continent: 'southAmerica',
      price: 'moderate',
      duration: 'long',
      image: '../images/destinations/Machu-Picchu.jpg',
      description: 'Journey to the ancient Incan citadel and discover Peru\'s rich history.',
      days: '7 Days',
      rating: '4.9/5 (150 reviews)',
      priceValue: '$999',
      popular: false
  },
  {
      id: 8,
      name: 'Sydney, Australia',
      continent: 'oceania',
      price: 'luxury',
      duration: 'long',
      image: '../images/destinations/Sydney.jpg',
      description: 'Experience the perfect mix of city life and beach culture in Sydney.',
      days: '8 Days',
      rating: '4.8/5 (170 reviews)',
      priceValue: '$1399',
      popular: false
  },
  {
      id: 9,
      name: 'Marrakech, Morocco',
      continent: 'africa',
      price: 'moderate',
      duration: 'medium',
      image: '../images/destinations/Marrackech.jpg',
      description: 'Lose yourself in the magical souks and riads of ancient Marrakech.',
      days: '5 Days',
      rating: '4.7/5 (130 reviews)',
      priceValue: '$699',
      popular: false
  },
  {
      id: 10,
      name: 'Reykjavik, Iceland',
      continent: 'europe',
      price: 'luxury',
      duration: 'medium',
      image: '../images/destinations/Reykjavik.jpg',
      description: 'Chase the Northern Lights and explore dramatic landscapes in Iceland.',
      days: '6 Days',
      rating: '4.9/5 (140 reviews)',
      priceValue: '$1199',
      popular: false
  },
  {
      id: 11,
      name: 'Bangkok, Thailand',
      continent: 'asia',
      price: 'budget',
      duration: 'medium',
      image: '../images/destinations/Bangkok.jpg',
      description: 'Experience the vibrant street life and ancient temples of Thailand\'s capital.',
      days: '5 Days',
      rating: '4.6/5 (200 reviews)',
      priceValue: '$499',
      popular: false
  },
  {
      id: 12,
      name: 'Vancouver, Canada',
      continent: 'northAmerica',
      price: 'moderate',
      duration: 'medium',
      image: '../images/destinations/Vancouver.jpg',
      description: 'Discover the perfect blend of urban life and natural beauty.',
      days: '6 Days',
      rating: '4.8/5 (160 reviews)',
      priceValue: '$899',
      popular: false
  }
];
